### ISSUE TITLE
help

### ISSUE THREAD

**Issue by drknowi11** [pk-1337/FiveM-Paid-Anticheats#1]
[    c-scripting-core] Creating script environments for rd_ac
[        script:rd_ac]  [MIXAS AntiCheat]  ClientConfig Refresh 
[        script:rd_ac]  [MIXAS AntiCheat]  TriggerConfig Refresh 
[        script:rd_ac]  [MIXAS AntiCheat]  ServerConfig Refresh 
[        script:rd_ac]  [MIXAS AntiCheat]  EntityConfig Refresh 
[        script:rd_ac] Error parsing script @rd_ac/server.lua in resource rd_ac: @rd_ac/server.lua:89: <break> at line 80 not inside a loop
[    c-scripting-core] Failed to load script server.lua.

**Comment by pk-1337** [comment]
Yo, like i said in readme: "Source deobfuscated so its shitty but readable"
Its deobfuscated so it wont work because deobfuscator did changes in it asda sd sadas dasd asd asd

**Comment by drknowi11** [comment]
ah okay but any idea to copy that function and write it anywhere else to make it work again (only some functions)
